#Request field constants
string ROBOT_FETCH=FETCH
string ROBOT_PAL=TIAGO
string ROBOT_VOLTA=VOLTA
# Request field
float32 m_per_sec
string robot_name
---
#Respose field constants
float32 CONVERSION_FACTOR=3.6
#Response field
float32 kmph
string received_robot_name

